#!/bin/bash
# Quick usage script for the metadata extractor

echo "Metadata Extractor Usage Examples:"
echo "=================================="
echo ""
echo "Basic usage:"
echo "python metadata_extractor.py filename.mp4"
echo ""
echo "Save output to file:"
echo "python metadata_extractor.py filename.mp4 > metadata_output.json"
echo ""
echo "Install optional dependencies for enhanced extraction:"
echo "pip install -r requirements.txt"
echo ""
echo "Examples with your files:"
echo "python metadata_extractor.py \"Download.mp4\""
echo "python metadata_extractor.py \"Download(1).mp4\""
echo ""
echo "To extract metadata from all MP4 files:"
echo "for file in *.mp4; do"
echo "    echo \"Processing: \$file\""
echo "    python metadata_extractor.py \"\$file\" > \"\${file%.*}_metadata.json\""
echo "done"
